# Generated by Django 3.0.3 on 2021-04-25 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('date', models.DateField(auto_created=True)),
                ('_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Timeslot',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('started_at', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=45000)),
            ],
        ),
        migrations.CreateModel(
            name='Screening',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('id_date', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='screening_app.Date')),
                ('id_room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='screening_app.Room')),
                ('id_timeslot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='screening_app.Timeslot')),
            ],
            options={
                'unique_together': {('id_timeslot', 'id_room', 'id_date')},
            },
        ),
    ]
