# Generated by Django 3.0.3 on 2021-05-03 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('screening_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='screening',
            name='id_date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='screening_app.Date'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='id_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='screening_app.Room'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='id_timeslot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='screening_app.Timeslot'),
        ),
    ]
