# Generated by Django 3.0.3 on 2021-05-03 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screening_app', '0002_auto_20210503_2319'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together={('started_at', 'duration')},
        ),
    ]
