# Generated by Django 3.0.3 on 2021-05-03 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screening_app', '0003_auto_20210503_2329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='price',
        ),
    ]
