# Generated by Django 3.0.3 on 2021-05-03 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening_app', '0004_remove_timeslot_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='price',
            field=models.IntegerField(default=45000),
        ),
    ]
