# Generated by Django 3.2 on 2021-05-05 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening_app', '0005_timeslot_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='date',
            field=models.DateField(auto_created=True, unique=True),
        ),
    ]
