# Generated by Django 3.2 on 2021-05-05 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening_app', '0006_alter_date_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='date',
            name='day',
            field=models.CharField(default='Monday', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='date',
            unique_together={('date', 'day')},
        ),
    ]
