# Generated by Django 3.2 on 2021-05-05 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening_app', '0007_auto_20210505_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='started_at',
            field=models.TimeField(unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='duration',
        ),
    ]
