# Generated by Django 3.2 on 2021-05-06 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening_app', '0008_auto_20210505_2140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='screening',
            old_name='id_date',
            new_name='date_id',
        ),
        migrations.RenameField(
            model_name='screening',
            old_name='id_room',
            new_name='room_id',
        ),
        migrations.RenameField(
            model_name='screening',
            old_name='id_timeslot',
            new_name='timeslot_id',
        ),
        migrations.AddField(
            model_name='screening',
            name='movie_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='screening',
            unique_together={('timeslot_id', 'room_id', 'date_id')},
        ),
    ]
